site_name: Facultad de Informática - FIC

copyright: Copyright &copy; 2023 - 2026 Facultad de Informática –
  <a href="#__consent">Configuración de cookies</a>

theme:
  name: material
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  logo: assets/favicon.png
  language: es

extra:
  generator: false
  social:
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fic-udc.bsky.social
    - icon: fontawesome/brands/telegram
      link: https://t.me/+mKQjdKvmhEJlNWVk
    - icon: fontawesome/brands/linkedin
      link: https://es.linkedin.com/in/ficudc
  analytics:
    provider: google
    property: G-J3RS5DMQ4K
  consent:
    title: Consentimiento de cookies
    description: >- 
      Utilizamos cookies para reconocer sus preferencias y visitas repetidas, así como
      para medir la efectividad de la información mostrada y si los usuarios
      encuentran lo que están buscando. Con su consentimiento, está ayudando a que
      nuestra facultad mejore.
nav:
  - Home: index.md
  - Información General:
    - Calendario: info_general/calendarios.md
  - Infomación Administración:
    #- Documentos: info_administracion/documentos.md
    - Atención al público: info_administracion/horarios.md
    - Estudios de Grado: info_administracion/estudios_grado.md
    - Estudios de Master: info_administracion/estudios_master.md
    - Tramites en Secretaría: info_administracion/tramites_secretaria.md
  - Grado en Ingeniería Informática:
    - Horarios y exámenes: gei/horariosExamenes.md
  - Grado en Ciencia e Ingeniería de datos:
    - Horarios y exámenes: gced/horariosExamenes.md
  - Grado en Inteligencia Artificial:
    - Horarios y exámenes: gia/horariosExamenes.md
  - Master Universitario en Ingeniería Informática:
    - Horarios y exámenes: muei/horariosExamenes.md
  - Otros estudios de máster:
    - Enlaces: otros_master/enlaces.md

markdown_extensions:
  - toc:
      title: En esta página
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  